// 按需导入
import Vue from 'vue'
import { tabs, tab, Dialog, checkbox, ActionSheet, rate, Lazyload, Icon, Button, Switch, Tabbar, TabbarItem, NavBar, Toast, Search, Swipe, SwipeItem, Grid, GridItem } from 'vant'
Vue.use(Button)
Vue.use(Switch)
Vue.use(Tabbar)
Vue.use(TabbarItem)
Vue.use(NavBar)
Vue.use(Toast)
Vue.use(GridItem)
Vue.use(Search)
Vue.use(Swipe)
Vue.use(SwipeItem)
Vue.use(Grid)
Vue.use(Icon)
Vue.use(Lazyload)
Vue.use(rate)
Vue.use(ActionSheet)
Vue.use(checkbox)
Vue.use(Dialog)
Vue.use(tabs)
Vue.use(tab)
